version: '3.8'

services:
  client:
    image: 'nginx'
    volumes:
      - ./lessons/test-endpoint/client/dist/:/usr/share/nginx/html
    ports:
      - '8080:80'
    depends_on:
      - server

  server:
    image: 'node:16-alpine'
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @test-endpoint/app start
    environment:
      - NODE_ENV=dev
    ports:
      - '4000:4000'
